changelog:
  exclude:
    labels:
      - release
      - ignore-changelog
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Feature Updates 🛠
      labels:
        - update
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Refactorings ♻️
      labels:
        - refactor
    - title: Dependency Updates 📦
      labels:
        - dependencies
    - title: Other Changes 📋
      labels:
        - other