let japaneseLocalization: [LocalizedKey: String] = [
    .localeCode: "ja",
    .day : "日目",
    .daysLater : "日後",
    .fromToday : "本日起算",
    .pinned : "ピン留めしました。",
    .alreadyRegistered: "既に登録されています。",
    .pinnedNothing : "ピン留めされた日数がありません。",
    .pinnedTip : "💡ヒント\nメイン画面でピン留めボタンを押すと、この画面で複数の日付をまとめて表示できます。",
    .confirmDelete : "削除してもよろしいですか？",
    .delete : "削除",
    .cancel : "キャンセル",
    .confirmComplication : "コンプリケーションを更新しますか？",
    .update : "更新",
    .widgetDay : "日目",
    .widgetDaysLater : "日後",
]
