let englishLocalization: [LocalizedKey: String] = [
    .localeCode: "en",
    .day : "day",
    .daysLater : "days later",
    .fromToday : "From Today",
    .pinned : "Pinned.",
    .alreadyRegistered : "Already registered.",
    .pinnedNothing : "There are no days pinned.",
    .pinnedTip : "💡Tip\nBy pressing the pin button on the main screen, you can display multiple dates together on this screen.",
    .confirmDelete : "Are you sure you want to delete?",
    .delete : "Delete",
    .cancel : "Cancel",
    .confirmComplication : "Do you want to update the Complication?",
    .update : "Update",
    .widgetDay : "D",
    .widgetDaysLater : "D L",
    .addWatchFace : "Add to watchface.",
    .selectWidgetNumber : "Select widget nunber.",
    .pinList : "Pin list",
]
