public enum AppStringKey: String, CaseIterable, Sendable {
    case day = "day"
    case dayLater = "day_later"
    case dayLaterMultiline = "day_later_multiline"
    case daysLater = "days_later"
    case fromToday = "from_today"
    case pinned = "pinned"
    case alreadyRegistered = "already_registered"
    case pinnedNothing = "pinned_nothing"
    case pinnedTip = "pinned_tip"
    case confirmDelete = "confirm_delete"
    case delete = "delete"
    case cancel = "cancel"
    case confirmComplication = "confirm_complication"
    case update = "update"
    case widgetDay = "widget_day"
    case widgetDaysLater = "widget_days_later"
    case widgetDescription = "widget_description"
    case addWatchFace = "add_watch_face"
    case selectWidgetNumber = "select_widget_number"
    case pinList = "pin_list"
    case calculate = "calculate"
    case pinnedItem = "pinned_item"
    case addToComplications = "add_to_complications"
}
